"""Error response contract — matches the `Error` schema in docs/api/openapi.yaml and the
conventions defined in docs/product/03-technical-specifications.md §2.

`request_id` is a per-request UUID for now, generated by `RequestIdMiddleware`. It is deliberately
named/shaped to be a drop-in replacement for an OpenTelemetry trace ID once
docs/architecture/05-infra-and-observability.md's tracing stack is wired up (Phase 1 Infrastructure
milestone) — call sites never need to change, only the middleware's implementation.
"""

import uuid
from collections.abc import Awaitable, Callable
from contextvars import ContextVar
from enum import StrEnum
from typing import Any

from fastapi import FastAPI, Request, status
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import Response

_request_id: ContextVar[str] = ContextVar("_request_id", default="")


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ApiError(Exception):
    def __init__(
        self, code: ErrorCode, message: str, *, status_code: int, details: dict[str, Any] | None = None
    ):
        self.code = code
        self.message = message
        self.status_code = status_code
        self.details = details
        super().__init__(message)


class NotFoundError(ApiError):
    def __init__(self, message: str = "Resource not found"):
        super().__init__(ErrorCode.NOT_FOUND, message, status_code=status.HTTP_404_NOT_FOUND)


class ConflictError(ApiError):
    def __init__(self, message: str = "Conflict", details: dict[str, Any] | None = None):
        super().__init__(ErrorCode.CONFLICT, message, status_code=status.HTTP_409_CONFLICT, details=details)


class UnauthorizedError(ApiError):
    def __init__(self, message: str = "Unauthorized"):
        super().__init__(ErrorCode.UNAUTHORIZED, message, status_code=status.HTTP_401_UNAUTHORIZED)


class ForbiddenError(ApiError):
    def __init__(self, message: str = "Forbidden"):
        super().__init__(ErrorCode.FORBIDDEN, message, status_code=status.HTTP_403_FORBIDDEN)


class RateLimitedError(ApiError):
    def __init__(self, message: str = "Rate limit exceeded"):
        super().__init__(ErrorCode.RATE_LIMITED, message, status_code=status.HTTP_429_TOO_MANY_REQUESTS)


class RequestIdMiddleware(BaseHTTPMiddleware):
    async def dispatch(
        self, request: Request, call_next: Callable[[Request], Awaitable[Response]]
    ) -> Response:
        request_id = str(uuid.uuid4())
        token = _request_id.set(request_id)
        try:
            response = await call_next(request)
        finally:
            _request_id.reset(token)
        response.headers["X-Request-Id"] = request_id
        return response


def get_request_id() -> str:
    return _request_id.get()


def _error_body(code: ErrorCode, message: str, details: dict[str, Any] | None) -> dict[str, Any]:
    return {
        "error": {
            "code": code.value,
            "message": message,
            "details": details,
            "request_id": get_request_id(),
        }
    }


def register_exception_handlers(app: FastAPI) -> None:
    @app.exception_handler(ApiError)
    async def handle_api_error(request: Request, exc: ApiError) -> JSONResponse:
        return JSONResponse(
            status_code=exc.status_code,
            content=_error_body(exc.code, exc.message, exc.details),
        )

    @app.exception_handler(Exception)
    async def handle_unexpected_error(request: Request, exc: Exception) -> JSONResponse:
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content=_error_body(ErrorCode.INTERNAL_ERROR, "An unexpected error occurred", None),
        )
